# Generated by Django 3.1.4 on 2021-03-21 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='love',
            field=models.ManyToManyField(null=True, related_name='love', to=settings.AUTH_USER_MODEL),
        ),
    ]
