# Generated by Django 3.1.4 on 2021-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20210321_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.TextField(default='General', max_length=250, null=True),
        ),
    ]
