# Generated by Django 3.1.4 on 2021-03-22 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='love',
            field=models.ManyToManyField(related_name='love', to=settings.AUTH_USER_MODEL),
        ),
    ]
